# config.yml

backend:
  name: github
  repo: joelazwar/joelazwar.github.io
  branch: master
  site_domain: stoic-clarke-422402.netlify.com
  publish_mode: editorial_workflow

media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Cover Image (Optional)', name: 'cover', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
